### ISSUE TITLE
replica dataset link not accessible 

### ISSUE THREAD

**Issue by Golbstein** [thucz/splatter360#2]
![image](https://github.com/user-attachments/assets/b1bba16e-a6ca-40a4-b5cb-a292ec0d13c8)

**Comment by thucz** [comment]
Hi! The link is attached with the extracting code. `https://pan.baidu.com/s/1_GWfDn3XfNffZNvXoJUZ9Q?pwd=bair`. The Code is `bair`.

**Comment by Golbstein** [comment]
thanks, but I still can't download the dataset.. it requires to install BaiduDisk and everything in Chinese and asks to create new account (with Chinese phone number)
Can you maybe share a direct download link?

**Comment by Golbstein** [comment]
![Screenshot 2024-12-11 at 12 04 21](https://github.com/user-attachments/assets/1bda3bd1-bfe0-41c7-a2f1-4a1de3d1bbce)

**Comment by Golbstein** [comment]
Maybe you can create a subset from the train/test dataset so it will be easier and faster to download and play with it? Thanks

**Comment by Golbstein** [comment]
![image](https://github.com/user-attachments/assets/ea609049-78f9-4a1f-bc2d-ec6c726a86e5)

**Comment by thucz** [comment]
I upload them into [OneDrive](https://1drv.ms/f/c/3e01a23b343bc186/EpTo7XbTMNhAsJNAu7pxsS8BPtHjq8v0prpc6aXN6Hid4g?e=6W62sq).

I will try to upload a subset.
