### ISSUE TITLE
image_cubes_input VS image_cubes_supervise

### ISSUE THREAD

**Issue by Golbstein** [thucz/splatter360#4]
What's the purpose of image_cubes_input?
From what I'm seeing the `extrinsics_cubes` represent `image_cubes_supervise`
So why do we need `image_cubes_input`?

<img width="715" alt="image" src="https://github.com/user-attachments/assets/1bddda44-4555-4bde-b827-058c0e529139" />

**Comment by thucz** [comment]
We input the `images_cubes_input` into our multi-view transformer and single-view depth encoder to reduce spherical distortion of equirectangular images. 

And we need to transform cube-map feature maps back to equirectangular features. However, the equirectangular-to-cube-map  conversion function `src.geometry.layers.Cube2Equirec` needs a specific image order which is different from image_cubes_supervise. So we change the orders of `image_cubes_supervise` into `image_cubes_input`.

**Comment by thucz** [comment]
You are right. This is also needed by the `src.geometry.layers.Cube2Equirec` function.

**Comment by thucz** [comment]
transformation process: `https://github.com/thucz/splatter360/blob/main/src/dataset/dataset_hm3d.py#L204-L213`

**Comment by Golbstein** [comment]
Wouldn't it be more efficient to reorder the images within `src.geometry.layers.Cube2Equirec` rather than creating two nearly identical tensors, in order to save GPU memory?

I appreciate the quick responses!

**Comment by thucz** [comment]
> Wouldn't it be more efficient to reorder the images within `src.geometry.layers.Cube2Equirec` rather than creating two nearly identical tensors, in order to save GPU memory?
> 
> I appreciate the quick responses!

One way is to revise `src.geometry.layers.Cube2Equirec` directly now to make it suitable for `image_cubes_supervise`. I recently have no time to revise this place.

**Comment by Golbstein** [comment]
maybe I'll do it later
thank you very much
